-- ============================================================
-- DATABASE SISTEM KEAHLIAN
-- Jalankan script ini di Supabase > SQL Editor
-- ============================================================

create table if not exists public.ahli (
  id uuid primary key default gen_random_uuid(),
  no_ahli bigint generated by default as identity unique not null,
  nama_penuh text not null,
  no_ic text not null unique,
  no_telefon text not null,
  alamat text not null,
  status text not null default 'aktif'
    check (status in ('aktif', 'tidak aktif')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Index untuk carian.
create index if not exists ahli_nama_idx on public.ahli (nama_penuh);
create index if not exists ahli_status_idx on public.ahli (status);

-- Function untuk updated_at.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists ahli_set_updated_at on public.ahli;

create trigger ahli_set_updated_at
before update on public.ahli
for each row
execute function public.set_updated_at();

-- ============================================================
-- RLS
-- ============================================================
alter table public.ahli enable row level security;

-- POLISI UNTUK TEST SAHAJA.
-- Ini membolehkan frontend tanpa login membaca/memasukkan/
-- mengemaskini/memadam data. Jangan guna polisi ini untuk
-- sistem sebenar yang mengandungi data peribadi.
drop policy if exists "test_select_ahli" on public.ahli;
drop policy if exists "test_insert_ahli" on public.ahli;
drop policy if exists "test_update_ahli" on public.ahli;
drop policy if exists "test_delete_ahli" on public.ahli;

create policy "test_select_ahli"
on public.ahli for select
to anon, authenticated
using (true);

create policy "test_insert_ahli"
on public.ahli for insert
to anon, authenticated
with check (true);

create policy "test_update_ahli"
on public.ahli for update
to anon, authenticated
using (true)
with check (true);

create policy "test_delete_ahli"
on public.ahli for delete
to anon, authenticated
using (true);

-- Contoh data ujian (optional)
-- insert into public.ahli (nama_penuh, no_ic, no_telefon, alamat)
-- values ('Ali Bin Abu', '900101-01-1234', '012-3456789', 'Kuala Lumpur');
